---
- name: clone aiida-importer repo
  git:
    repo: https://github.com/ltalirz/aiida-importer
    dest: "{{ ansible_env.HOME }}/aiida-importer"
    accept_hostkey: yes
    force: yes
  register: git_checkout

- name: Install pip packages
  pip:
    name: "{{ ansible_env.HOME }}/aiida-importer"
    virtualenv: "{{ aiida_venv }}"
  register: pip_install

- include_role:
    name: marvel-nccr.current-user
  when: current_user is undefined

- name: copy aiida-importer apache config
  become: True
  template:
      src: "aiida-importer.conf"
      dest: /etc/apache2/sites-available/aiida-importer.conf
  vars:
    daemon_user: "{{ current_user }}"
    daemon_workdir: "{{ ansible_env.HOME }}/aiida-importer"
    daemon_aiida_venv: "{{ aiida_venv |  regex_replace('\\$\\{HOME}', current_user_home) }}"

- name: enable aiida-importer site
  become: True
  command: a2ensite aiida-importer
  args:
      creates:  /etc/apache2/sites-enabled/aiida-importer.conf
