---
- name: install apt dependencies
  become: true
  apt:
      name: 
        - nodejs
        - zip

- name: Get jmol
  get_url:
    url: "https://sourceforge.net/projects/jmol/files/Jmol/Version%2014.29/Jmol%2014.29.22/Jmol-14.29.22-binary.zip/download"
    dest: "{{ ansible_env.HOME }}/jmol.zip"
  register: jmol_download

- name: Extract jmol source
  unarchive:
    src: "{{ ansible_env.HOME }}/jmol.zip"
    dest: "{{ ansible_env.HOME }}/"
    remote_src: True
  when: jmol_download.changed

- name: Extract jsmol source
  unarchive:
    src: "{{ ansible_env.HOME }}/jmol-14.29.22/jsmol.zip"
    dest: "{{ ansible_env.HOME }}/jmol-14.29.22"
    remote_src: True
  when: jmol_download.changed


- name: clone bokeh-aiida-visualizer repo
  git:
    repo: https://github.com/ltalirz/bokeh-aiida-visualizer
    dest: "{{ ansible_env.HOME }}/bokeh-aiida-visualizer"
    accept_hostkey: yes
    force: yes
  register: git_checkout

- name: Install pip packages
  pip:
    name: "{{ ansible_env.HOME }}/bokeh-aiida-visualizer"
    virtualenv: "{{ aiida_venv }}"
    editable: True
  register: pip_install


- include_role:
    name: marvel-nccr.current-user
  when: current_user is undefined

- name: Add bokeh-aiida-visualizer as system service
  become: true
  template:
    src: aiida-bokeh-visualizer.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: 0644
  vars:
    daemon_user: "{{ current_user }}"
    daemon_workdir: "{{ ansible_env.HOME }}/bokeh-aiida-visualizer"
    daemon_aiida_venv: "{{ aiida_venv |  regex_replace('\\$\\{HOME}', current_user_home) }}"

- name: Start aiida-bokeh-visualizer system service
  become: true
  systemd:
    name: aiida-bokeh-visualizer
    enabled: true
    masked: false
    daemon-reload: true
    state: restarted
  when: not (cloud_platform is defined and cloud_platform == 'docker')

## Copy bokeh app
#WORKDIR /project/discover-cofs
#COPY figure ./figure
#COPY detail ./detail
#COPY select-figure ./select-figure
#RUN ln -s /project/jmol-14.29.22/jsmol ./detail/static/jsmol
#COPY setup.py import_db.py ./
#RUN pip install -e .
#COPY serve-app.sh /opt/
#
## start bokeh server
#EXPOSE 5006
#CMD ["/opt/serve-app.sh"]
